# Generated by Django 4.2.16 on 2026-09-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_id", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING_OPTIN", "PENDING_OPTIN"),
                            ("OPTED_IN", "OPTED_IN"),
                            ("ENROLLED", "ENROLLED"),
                            ("SENT", "SENT"),
                            ("SUPPRESSED", "SUPPRESSED"),
                        ],
                        default="PENDING_OPTIN",
                        max_length=20,
                    ),
                ),
                ("current_step_index", models.IntegerField(default=0)),
                (
                    "next_send_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FlowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "trigger_type",
                    models.CharField(default="cart_abandoned", max_length=64),
                ),
                ("steps", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_e164", models.CharField(max_length=20, unique=True)),
                ("country_code", models.CharField(max_length=4)),
                ("timezone", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SendRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_index", models.IntegerField()),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("worker_pid", models.IntegerField()),
                ("trial_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_records",
                        to="flows.enrollment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrollmentTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_state", models.CharField(max_length=20)),
                ("to_state", models.CharField(max_length=20)),
                ("reason", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="flows.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="flows.flowdefinition",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="flows.recipient",
            ),
        ),
        migrations.CreateModel(
            name="DeferredSendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_index", models.IntegerField()),
                ("deferred_from_utc", models.DateTimeField()),
                ("deferred_to_utc", models.DateTimeField()),
                ("recipient_local_time", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deferrals",
                        to="flows.enrollment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["state", "next_send_at"], name="ix_state_next_send_at"
            ),
        ),
    ]
